# 03 - Pandas

## Instalando biblioteca e importando

In [1]:
import dtale
!pip install pandas

Requirement already satisfied: pandas in ./.venv/lib/python3.9/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in ./.venv/lib/python3.9/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.9/site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.9/site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
# Importando as cotações de VALE3 através de um arquivo CSV remoto
vale3 = pd.read_csv('https://raw.githubusercontent.com/codigoquant/data/refs/heads/main/VALE3.csv')
vale3

,Date,Open,High,Low,Close,Adj Close,Volume
0,2019-10-21,46.419998,47.209999,46.259998,47.209999,44.145901,13486800.0
1,2019-10-22,47.279999,47.540001,47.099998,47.299999,44.230061,15194800.0
2,2019-10-23,47.599998,47.830002,47.029999,47.110001,44.052391,12362800.0
3,2019-10-24,47.459999,47.570000,46.520000,46.750000,43.715755,14646600.0
4,2019-10-25,47.750000,48.560001,47.549999,48.560001,45.408283,21754000.0
...,...,...,...,...,...,...,...
242,2020-10-13,61.270000,62.639999,61.029999,62.139999,62.139999,18602200.0
243,2020-10-14,62.080002,63.290001,62.040001,63.000000,63.000000,22210600.0
244,2020-10-15,62.410000,62.860001,61.980000,62.470001,62.470001,16309700.0
245,2020-10-16,62.700001,63.099998,62.240002,62.240002,62.240002,15783800.0
246,2020-10-19,62.730000,63.180000,61.950001,61.950001,61.950001,29276100.0

In [4]:
# Exibindo o tipo da variável vale3
type(vale3)

pandas.core.frame.DataFrame

In [5]:
# Exibindo as 5 primeiras linhas
vale3.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2019-10-21,46.419998,47.209999,46.259998,47.209999,44.145901,13486800.0
1,2019-10-22,47.279999,47.540001,47.099998,47.299999,44.230061,15194800.0
2,2019-10-23,47.599998,47.830002,47.029999,47.110001,44.052391,12362800.0
3,2019-10-24,47.459999,47.570000,46.520000,46.750000,43.715755,14646600.0
4,2019-10-25,47.750000,48.560001,47.549999,48.560001,45.408283,21754000.0

In [6]:
# Exibindo as 5 últimas linhas
vale3.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
242,2020-10-13,61.270000,62.639999,61.029999,62.139999,62.139999,18602200.0
243,2020-10-14,62.080002,63.290001,62.040001,63.000000,63.000000,22210600.0
244,2020-10-15,62.410000,62.860001,61.980000,62.470001,62.470001,16309700.0
245,2020-10-16,62.700001,63.099998,62.240002,62.240002,62.240002,15783800.0
246,2020-10-19,62.730000,63.180000,61.950001,61.950001,61.950001,29276100.0

In [7]:
# Selecionando a coluna com os preços máximos
vale3['High']

0      47.209999
1      47.540001
2      47.830002
3      47.570000
4      48.560001
         ...
242    62.639999
243    63.290001
244    62.860001
245    63.099998
246    63.180000
Name: High, Length: 247, dtype: float64

In [8]:
# Selecionando os preços máximos e de fechamento
vale3[['High', 'Close']]

          High      Close
0    47.209999  47.209999
1    47.540001  47.299999
2    47.830002  47.110001
3    47.570000  46.750000
4    48.560001  48.560001
..         ...        ...
242  62.639999  62.139999
243  63.290001  63.000000
244  62.860001  62.470001
245  63.099998  62.240002
246  63.180000  61.950001

[247 rows x 2 columns]

In [12]:
# Converte o índice para datetime e ordena por data
vale3.index = pd.to_datetime(vale3.index)
vale3 = vale3.set_index('Date')
vale3 = vale3.sort_index()

In [13]:
# Selecionando os preços em 15/10/2020
vale3.loc['2020-10-15']

Open         6.241000e+01
High         6.286000e+01
Low          6.198000e+01
Close        6.247000e+01
Adj Close    6.247000e+01
Volume       1.630970e+07
Name: 2020-10-15, dtype: float64

In [14]:
# Selecionando os preços em 15/10/2020 e 19/10/2020
vale3.loc[['2020-10-15', '2020-10-19']]

             Open       High        Low      Close  Adj Close      Volume
Date
2020-10-15  62.41  62.860001  61.980000  62.470001  62.470001  16309700.0
2020-10-19  62.73  63.180000  61.950001  61.950001  61.950001  29276100.0

In [15]:
# Selecionando os preços de abertura e fechamento em 15/10/2020 e 19/10/2020
vale3.loc[['2020-10-15', '2020-10-19']][['Open', 'Close']]

             Open      Close
Date
2020-10-15  62.41  62.470001
2020-10-19  62.73  61.950001

In [16]:
# Selecionando somente 2020 para frente
vale3.loc['2020':]

                 Open       High        Low      Close  Adj Close      Volume
Date
2020-01-02  53.980000  54.439999  53.750000  54.330002  52.150002  17509700.0
2020-01-03  53.680000  54.500000  53.580002  53.930000  51.766048  17284800.0
2020-01-06  53.799999  53.799999  53.150002  53.610001  51.458889  32787800.0
2020-01-07  53.500000  54.189999  53.400002  54.000000  51.833241  16326400.0
2020-01-08  54.200001  54.369999  53.619999  54.009998  51.842838  15298500.0
...               ...        ...        ...        ...        ...         ...
2020-10-13  61.270000  62.639999  61.029999  62.139999  62.139999  18602200.0
2020-10-14  62.080002  63.290001  62.040001  63.000000  63.000000  22210600.0
2020-10-15  62.410000  62.860001  61.980000  62.470001  62.470001  16309700.0
2020-10-16  62.700001  63.099998  62.240002  62.240002  62.240002  15783800.0
2020-10-19  62.730000  63.180000  61.950001  61.950001  61.950001  29276100.0

[200 rows x 6 columns]

In [17]:
# Fevereiro e Março
vale3.loc['2020-02':'2020-04']

                 Open       High        Low      Close  Adj Close      Volume
Date
2020-02-03  50.500000  51.090000  49.799999  50.910000  48.867226  18858200.0
2020-02-04  52.200001  52.580002  51.970001  52.270000  50.172657  21559200.0
2020-02-05  53.320000  53.619999  52.990002  52.990002  50.863770  26797700.0
2020-02-06  53.660000  53.919998  52.820000  53.279999  51.142128  22155800.0
2020-02-07  52.880001  52.959999  51.919998  52.099998  50.009476  14450900.0
2020-02-10  51.900002  51.900002  49.919998  50.189999  48.176117  28244800.0
2020-02-11  51.150002  52.200001  51.020000  52.049999  49.961483  27560600.0
2020-02-12  53.099998  53.380001  52.830002  53.070000  50.940556  28539800.0
2020-02-13  52.220001  52.400002  51.560001  52.139999  50.047871  20105600.0
2020-02-14  52.209999  52.279999  50.950001  51.000000  48.953617  19896200.0
2020-02-17  51.709999  53.410000  51.619999  53.410000  51.266914  28134200.0
2020-02-18  52.549999  53.049999  52.119999  52.799999  50.681389  18054400.0
2020-02-19  52.930000  53.119999  52.400002  52.810001  50.690990  14439700.0
2020-02-20  53.270000  53.490002  52.060001  52.200001  50.105465  18818800.0
2020-02-21  51.000000  51.139999  49.799999  50.130001  48.118526  32249900.0
2020-02-26        NaN        NaN        NaN        NaN        NaN         NaN
2020-02-27  44.650002  45.540001  43.560001  44.470001  42.685635  42419000.0
2020-02-28  43.990002  44.310001  43.200001  44.310001  42.532055  33228600.0
2020-03-02  44.880001  47.090000  44.810001  46.360001  44.499798  48372500.0
2020-03-03  46.740002  49.090000  46.070000  46.349998  44.490196  52401800.0
2020-03-04  48.000000  49.090000  47.000000  48.570000  46.621120  31476600.0
2020-03-05  47.660000  47.950001  45.950001  46.849998  44.970135  29092300.0
2020-03-06  44.200001  45.820000  43.650002  44.610001  42.820015  39718600.0
2020-03-09  40.450001  41.540001  37.810001  37.830002  36.312065  59037000.0
2020-03-10  41.900002  45.340000  40.799999  44.810001  43.011990  63269800.0
2020-03-11  43.009998  44.290001  39.000000  40.740002  39.105301  50025000.0
2020-03-12  36.000000  36.000000  32.450001  35.349998  33.931572  62222000.0
2020-03-13  42.000000  44.029999  37.000000  42.900002  41.178631  67635900.0
2020-03-16  36.009998  41.400002  36.009998  39.040001  37.473515  59078300.0
2020-03-17  40.500000  43.570000  39.110001  41.509998  39.844402  52743800.0
2020-03-18  38.799999  40.869999  35.700001  38.650002  37.099163  59689100.0
2020-03-19  37.500000  39.000000  35.259998  36.400002  34.939445  52645400.0
2020-03-20  37.900002  39.410000  34.709999  35.189999  33.777992  50479900.0
2020-03-23  35.549999  35.860001  33.369999  34.099998  32.731731  41958300.0
2020-03-24  36.860001  38.650002  36.860001  37.639999  36.129688  37044800.0
2020-03-25  38.189999  41.349998  38.090000  40.849998  39.210884  38064400.0
2020-03-26  41.009998  42.410000  39.990002  42.000000  40.314743  36253000.0
2020-03-27  39.299999  41.439999  39.200001  40.099998  38.490978  32331200.0
2020-03-30  40.919998  42.320000  40.740002  41.770000  40.093971  31298300.0
2020-03-31  42.299999  44.490002  42.220001  43.220001  41.485790  39238000.0

In [18]:
# Julho de 2020
vale3.loc['2020-07':'2020-08']

                 Open       High        Low      Close  Adj Close      Volume
Date
2020-07-01  56.080002  56.080002  54.049999  54.540001  52.351574  28999400.0
2020-07-02  54.849998  55.740002  54.750000  55.490002  53.263454  24148500.0
2020-07-03  55.200001  55.700001  54.930000  55.259998  53.042679   7831800.0
2020-07-06  56.090000  56.740002  55.590000  56.570000  54.300117  23609900.0
2020-07-07  56.740002  56.980000  56.099998  56.369999  54.108143  13598400.0
2020-07-08  56.900002  57.720001  55.790001  57.320000  55.020023  32634600.0
2020-07-09  57.520000  57.680000  56.060001  56.419998  54.156136  19741600.0
2020-07-10  56.520000  57.299999  56.160000  56.970001  54.684071  14728100.0
2020-07-13  57.730000  59.220001  57.650002  57.650002  55.336784  28780200.0
2020-07-14  57.919998  61.970001  57.900002  61.700001  59.224277  52234500.0
2020-07-15  62.299999  62.930000  60.389999  61.790001  59.310665  29833100.0
2020-07-16  61.299999  61.689999  59.849998  60.119999  57.707672  22788400.0
2020-07-17  60.500000  61.250000  60.320000  61.040001  58.590759  18896400.0
2020-07-20  61.119999  61.490002  60.349998  60.799999  58.360386  16491500.0
2020-07-21  60.439999  60.480000  59.270000  59.700001  57.304527  29043600.0
2020-07-22  59.930000  60.250000  58.799999  59.240002  56.862984  19644700.0
2020-07-23  59.900002  60.160000  58.639999  58.849998  56.488632  17291900.0
2020-07-24  58.570000  58.849998  57.820000  58.599998  56.248661  22544100.0
2020-07-27  59.099998  61.630001  58.980000  61.369999  58.907516  35124800.0
2020-07-28  60.700001  61.160000  60.200001  60.340000  57.918846  21707500.0
2020-07-29  61.209999  62.950001  60.849998  62.950001  60.424118  29486600.0
2020-07-30  62.299999  62.369999  60.650002  61.270000  58.811531  32210700.0
2020-07-31  61.099998  62.209999  60.500000  60.709999  58.273998  26318800.0

In [19]:
# 13 a 23 de dezembro de 2019
vale3.loc['2019-12-13':'2019-12-23']

                 Open       High        Low      Close  Adj Close      Volume
Date
2019-12-13  53.299999  54.000000  52.840000  53.759998  50.270782  28172500.0
2019-12-16  54.500000  54.669998  53.340000  53.340000  49.878044  21806800.0
2019-12-17  53.250000  53.709999  53.049999  53.419998  49.952850  13570300.0
2019-12-18  53.279999  53.540001  52.599998  53.470001  49.999607  22924500.0
2019-12-19  53.500000  54.240002  53.220001  54.000000  50.495205  17683200.0
2019-12-20  54.770000  54.990002  54.150002  54.790001  51.233932  42124200.0
2019-12-23  54.900002  54.980000  54.400002  54.580002  51.037563  10225700.0

In [21]:
# Selecionando a primeira linha
vale3.iloc[0]

Open         4.642000e+01
High         4.721000e+01
Low          4.626000e+01
Close        4.721000e+01
Adj Close    4.414590e+01
Volume       1.348680e+07
Name: 2019-10-21, dtype: float64

In [22]:
# Selecionando a última linha
vale3.iloc[-1]

Open         6.273000e+01
High         6.318000e+01
Low          6.195000e+01
Close        6.195000e+01
Adj Close    6.195000e+01
Volume       2.927610e+07
Name: 2020-10-19, dtype: float64

In [23]:
# Selecionando as 3 primeiras linhas
vale3.iloc[:3]

                 Open       High        Low      Close  Adj Close      Volume
Date
2019-10-21  46.419998  47.209999  46.259998  47.209999  44.145901  13486800.0
2019-10-22  47.279999  47.540001  47.099998  47.299999  44.230061  15194800.0
2019-10-23  47.599998  47.830002  47.029999  47.110001  44.052391  12362800.0

In [24]:
# Selecionando as 3 últimas linhas
vale3.iloc[-3:]

                 Open       High        Low      Close  Adj Close      Volume
Date
2020-10-15  62.410000  62.860001  61.980000  62.470001  62.470001  16309700.0
2020-10-16  62.700001  63.099998  62.240002  62.240002  62.240002  15783800.0
2020-10-19  62.730000  63.180000  61.950001  61.950001  61.950001  29276100.0

In [25]:
# Selecionando as linhas 0, 6 e 8
vale3.iloc[[0, 6, 8]]

                 Open       High        Low      Close  Adj Close      Volume
Date
2019-10-21  46.419998  47.209999  46.259998  47.209999  44.145901  13486800.0
2019-10-29  48.410000  48.799999  48.080002  48.650002  45.492443  10091200.0
2019-10-31  48.099998  48.480000  46.860001  47.200001  44.136551  21765000.0

In [26]:
# Selecionando primeira e segunda colunas
# vale3.iloc[linha_inicial:linha_final, coluna_inicial:coluna_final]
vale3.iloc[:, :2]

                 Open       High
Date
2019-10-21  46.419998  47.209999
2019-10-22  47.279999  47.540001
2019-10-23  47.599998  47.830002
2019-10-24  47.459999  47.570000
2019-10-25  47.750000  48.560001
...               ...        ...
2020-10-13  61.270000  62.639999
2020-10-14  62.080002  63.290001
2020-10-15  62.410000  62.860001
2020-10-16  62.700001  63.099998
2020-10-19  62.730000  63.180000

[247 rows x 2 columns]

In [28]:
# Ler arquivo CSV com Pandas e definir a coluna 0 como índice
URL = 'https://media.githubusercontent.com/media/codigoquant/data/refs/heads/main/indicadores_fundamentalistas.csv'

empresas = pd.read_csv(URL, index_col=0)

# Exiba o conteúdo do arquivo
empresas

,Papel,Cotação,P/L,P/VP,PSR,Div.Yield,P/Ativo,P/Cap.Giro,P/EBIT,P/Ativ Circ.Liq,...,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
0,MRSA6B,0.00,0.00,0.00,0.000,0.0000,0.000,0.00,0.00,0.00,...,0.00,0.0000,0.0000,0.00,0.0000,0.0675,0.0,4.306220e+09,0.00,0.0004
1,CSTB3,150.00,0.00,0.00,0.000,0.0000,0.000,0.00,0.00,0.00,...,0.00,0.4085,0.2898,2.60,0.2240,0.2011,0.0,8.420670e+09,0.14,0.3191
2,PORP4,2.40,0.00,0.00,0.000,0.0000,0.000,0.00,0.00,0.00,...,0.00,0.0000,0.0000,0.00,0.0000,-0.0208,0.0,2.239900e+07,0.00,0.1366
3,IVTT3,0.00,0.00,0.00,0.000,0.0000,0.000,0.00,0.00,0.00,...,0.00,0.0000,0.0000,0.00,0.0000,-0.0040,0.0,1.083050e+09,0.00,0.2067
4,EQMA6B,0.00,0.00,0.00,0.000,0.0000,0.000,0.00,0.00,0.00,...,0.00,0.0000,0.0000,0.00,0.0000,0.2037,0.0,3.230000e+09,0.00,0.0652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,GUAR4,151.00,1661.32,15.52,11.645,0.0000,5.746,30.19,-766.71,-186.18,...,189.56,-0.0152,0.0070,1.47,-0.0106,0.0093,0.0,4.855730e+09,0.93,0.0403
929,APER3,48.39,5446.25,3.10,5.514,0.0011,1.886,15.33,-1663.23,-15.05,...,78.27,-0.0033,0.0010,1.86,-0.0014,0.0006,1519070.0,1.790790e+08,0.00,-0.0808
930,BIDI3,52.90,30497.10,12.44,0.000,0.0010,0.000,0.00,0.00,0.00,...,0.00,0.0000,0.0000,0.00,0.0000,0.0004,18231400.0,3.251960e+09,0.00,0.1723
931,BIDI11,159.55,30660.40,12.50,0.000,0.0010,0.000,0.00,0.00,0.00,...,0.00,0.0000,0.0000,0.00,0.0000,0.0004,172312000.0,3.251960e+09,0.00,0.1723
932,BIDI4,53.46,30819.90,12.57,0.000,0.0010,0.000,0.00,0.00,0.00,...,0.00,0.0000,0.0000,0.00,0.0000,0.0004,112801000.0,3.251960e+09,0.00,0.1723

In [30]:
# Criando filtro de empresas com liquidez maior que 1B
filtro = empresas['Liq.2meses'] > 1000000000

# Listando as empresas com o filtro
empresas[filtro]

,Papel,Cotação,P/L,P/VP,PSR,Div.Yield,P/Ativo,P/Cap.Giro,P/EBIT,P/Ativ Circ.Liq,...,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
122,PETR4,28.11,-8.22,1.48,1.359,0.0000,0.380,33.52,4.16,-0.65,...,4.80,0.3271,-0.1693,1.08,0.1019,-0.1801,1.808040e+09,2.477360e+11,1.81,-0.0045
655,BBDC4,25.32,13.57,1.56,0.000,0.0276,0.000,0.00,0.00,0.00,...,0.00,0.0000,0.0000,0.00,0.0000,0.1151,1.153560e+09,1.437030e+11,0.00,-0.0927
661,ITUB4,27.56,14.25,1.98,0.000,0.0491,0.000,0.00,0.00,0.00,...,0.00,0.0000,0.0000,0.00,0.0000,0.1387,1.095040e+09,1.366990e+11,0.00,-0.2996
806,VALE3,94.01,32.09,2.55,2.912,0.0256,1.101,12.84,6.43,-3.01,...,5.68,0.4526,0.0726,1.64,0.2012,0.0795,2.770660e+09,1.946400e+11,0.44,0.1701

In [36]:
# Ordenando empresas por menores P/L
empresas.sort_values('P/L')[['Papel', 'P/L']]

      Papel       P/L
21    CTSA3 -16625.30
22    CTSA4 -13286.30
23    CTSA8  -6956.19
24   BBTG12  -5910.80
25    OMGE3  -3772.83
..      ...       ...
928   GUAR4   1661.32
929   APER3   5446.25
930   BIDI3  30497.10
931  BIDI11  30660.40
932   BIDI4  30819.90

[933 rows x 2 columns]

In [65]:
# Ordenando empresas por maiores Dividend Yield
empresas.sort_values('Div.Yield', ascending=False)[['Papel', 'Div.Yield']]

     Papel  Div.Yield
436  TRPN3     1.0474
307  MMAQ4     0.7980
328  PEAB4     0.5792
88   CRDE3     0.5453
390  PEAB3     0.5443
..     ...        ...
321  CSPC4     0.0000
322  GALO4     0.0000
323  BERG3     0.0000
324  SFSA3     0.0000
466  VINE3     0.0000

[933 rows x 2 columns]

In [39]:
# Listando as 5 empresas com maior ROIC
empresas.sort_values('ROIC', ascending=False).head()[['Papel', 'ROIC']]

     Papel    ROIC
436  TRPN3  5.2301
147  ADHM3  5.2170
182  VTLM3  5.2170
415  BPHA3  4.0101
628  MPLU3  1.2957

In [47]:
# Listar as 5 empresas com menor EV/EBIT, excluindo EV/EBIT negativo
empresas[empresas['EV/EBIT'] > 0].sort_values('EV/EBIT').head()[['Papel', 'EV/EBIT']]

     Papel  EV/EBIT
425  TPRC3     0.01
313  CMMA4     0.03
456  MTBR4     0.03
377  MSAN3     0.21
315  MSAN4     0.21

In [50]:
# Colunas Papel e P/L das 10 empresas com menor P/L não negativo, e com Liq.2meses entre R$1 mi e R$ 10 mi
empresas[(empresas['Liq.2meses'] > 1000000) & (empresas['Liq.2meses'] < 10000000) & (empresas['P/L'] > 0)][['Papel', 'P/L']].sort_values('P/L')[:10]

     Papel    P/L
432  FHER3   0.34
511  SAPR3   6.47
529  TAEE4   7.07
534  GPCP3   7.59
585  SANB3  10.38
603  SANB4  11.15
621  JSLG3  11.86
660  ITSA3  14.24
663  POSI3  14.41
669  KEPL3  14.66

In [67]:
# Se for usar Google Colab: (melhor)
# from google.colab.data_table import DataTable
# DataTable(empresas, max_columns=25)

# Se for usar Jupyter:
!pip install itables
import itables
from itables import init_notebook_mode
itables.options.maxBytes = "256KB"
empresas = pd.read_csv(URL, index_col=0)
init_notebook_mode(all_interactive=True)
empresas

Requirement already satisfied: itables in ./.venv/lib/python3.9/site-packages (2.7.3)

      Papel  Cotação       P/L   P/VP     PSR  Div.Yield  P/Ativo  P/Cap.Giro  \
0    MRSA6B     0.00      0.00   0.00   0.000     0.0000    0.000        0.00
1     CSTB3   150.00      0.00   0.00   0.000     0.0000    0.000        0.00
2     PORP4     2.40      0.00   0.00   0.000     0.0000    0.000        0.00
3     IVTT3     0.00      0.00   0.00   0.000     0.0000    0.000        0.00
4    EQMA6B     0.00      0.00   0.00   0.000     0.0000    0.000        0.00
..      ...      ...       ...    ...     ...        ...      ...         ...
928   GUAR4   151.00   1661.32  15.52  11.645     0.0000    5.746       30.19
929   APER3    48.39   5446.25   3.10   5.514     0.0011    1.886       15.33
930   BIDI3    52.90  30497.10  12.44   0.000     0.0010    0.000        0.00
931  BIDI11   159.55  30660.40  12.50   0.000     0.0010    0.000        0.00
932   BIDI4    53.46  30819.90  12.57   0.000     0.0010    0.000        0.00

      P/EBIT  P/Ativ Circ.Liq  ...  EV/EBITDA  Mrg Ebit  Mrg. Líq.  \
0       0.00             0.00  ...       0.00    0.0000     0.0000
1       0.00             0.00  ...       0.00    0.4085     0.2898
2       0.00             0.00  ...       0.00    0.0000     0.0000
3       0.00             0.00  ...       0.00    0.0000     0.0000
4       0.00             0.00  ...       0.00    0.0000     0.0000
..       ...              ...  ...        ...       ...        ...
928  -766.71          -186.18  ...     189.56   -0.0152     0.0070
929 -1663.23           -15.05  ...      78.27   -0.0033     0.0010
930     0.00             0.00  ...       0.00    0.0000     0.0000
931     0.00             0.00  ...       0.00    0.0000     0.0000
932     0.00             0.00  ...       0.00    0.0000     0.0000

     Liq. Corr.    ROIC     ROE   Liq.2meses   Patrim. Líq  Dív.Brut/ Patrim.  \
0          0.00  0.0000  0.0675          0.0  4.306220e+09               0.00
1          2.60  0.2240  0.2011          0.0  8.420670e+09               0.14
2          0.00  0.0000 -0.0208          0.0  2.239900e+07               0.00
3          0.00  0.0000 -0.0040          0.0  1.083050e+09               0.00
4          0.00  0.0000  0.2037          0.0  3.230000e+09               0.00
..          ...     ...     ...          ...           ...                ...
928        1.47 -0.0106  0.0093          0.0  4.855730e+09               0.93
929        1.86 -0.0014  0.0006    1519070.0  1.790790e+08               0.00
930        0.00  0.0000  0.0004   18231400.0  3.251960e+09               0.00
931        0.00  0.0000  0.0004  172312000.0  3.251960e+09               0.00
932        0.00  0.0000  0.0004  112801000.0  3.251960e+09               0.00

     Cresc. Rec.5a
0           0.0004
1           0.3191
2           0.1366
3           0.2067
4           0.0652
..             ...
928         0.0403
929        -0.0808
930         0.1723
931         0.1723
932         0.1723

[933 rows x 21 columns]